"""Dataset specifications: class names, domains and the standard leave-one-domain-out splits."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from dipt.paths import DATA_ROOT, resolve


@dataclass(frozen=True)
class DatasetSpec:
    """Static description of a prepared dataset."""

    name: str
    dirname: str
    classnames: list[str]
    domains: list[str]
    val_domain: str
    #: Leave-one-domain-out protocol: (train domains, test domain) pairs.
    #: The validation domain is held out of every split.
    splits: list[tuple[list[str], str]] = field(default_factory=list)
    description: str = ""

    @property
    def num_classes(self) -> int:
        return len(self.classnames)

    @property
    def num_domains(self) -> int:
        return len(self.domains)

    def root(self, data_root: str | Path | None = None) -> Path:
        """Absolute path of the prepared dataset directory."""
        base = resolve(data_root) if data_root is not None else DATA_ROOT
        return Path(base) / self.dirname

    def train_domains_of(self, test_domain: str) -> list[str]:
        """All domains except the test domain and the validation domain."""
        return [d for d in self.domains if d not in (str(test_domain), self.val_domain)]


CAMELYON17 = DatasetSpec(
    name="camelyon17",
    dirname="camelyon17",
    classnames=["normal", "tumor"],
    domains=["0", "1", "2", "3", "4"],
    # The paper reserves one center (hospital 2 == index 1) for validation in
    # both the prompt-learning and the distillation stage.
    val_domain="1",
    splits=[
        (["0", "2", "3"], "4"),
        (["0", "2", "4"], "3"),
        (["0", "3", "4"], "2"),
        (["2", "3", "4"], "0"),
    ],
    description="Camelyon17-WILDS: breast-cancer lymph-node patches from 5 hospitals.",
)

KATHER19 = DatasetSpec(
    name="kather19",
    dirname="kather19",
    classnames=["ADI", "BACK", "DEB", "LYM", "MUC", "MUS", "NORM", "STR", "TUM"],
    # 5 domains total, mirroring Camelyon17's shape: domains 0-3 rotate cleanly
    # through leave-one-out (train in 3 splits, test in 1), domain 4 is held out
    # purely for validation. Domain "5" (a 6th stain-augmented pseudo-domain) is
    # generated by prepare_kather_domains.py but intentionally unused here.
    domains=["0", "1", "2", "3", "4"],
    val_domain="4",
    splits=[
        (["0", "1", "2"], "3"),
        (["0", "1", "3"], "2"),
        (["0", "2", "3"], "1"),
        (["1", "2", "3"], "0"),
    ],
    description="Kather19 (NCT-CRC-HE-100K) colorectal patches, 9 tissue types, "
    "stain-augmented pseudo-domains (see scripts/prepare_kather_domains.py).",
)

DATASETS: dict[str, DatasetSpec] = {
    CAMELYON17.name: CAMELYON17,
    KATHER19.name: KATHER19,
}


def get_dataset_spec(name: str) -> DatasetSpec:
    try:
        return DATASETS[name]
    except KeyError:
        raise KeyError(f"Unknown dataset '{name}'. Available: {sorted(DATASETS)}") from None
